package com.garganttua.core.mapper;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import com.garganttua.core.observability.Logger;
import com.garganttua.core.mapper.annotations.FieldMappingRule;
import com.garganttua.core.mapper.annotations.MappingIgnore;
import com.garganttua.core.mapper.annotations.ObjectMappingRule;
import com.garganttua.core.mapper.rules.ImplicitConversionMappingExecutor;
import com.garganttua.core.mapper.rules.ImplicitConversions;
import com.garganttua.core.mapper.rules.MapableCollectionMappingExecutor;
import com.garganttua.core.mapper.rules.MapableMapMappingExecutor;
import com.garganttua.core.mapper.rules.MethodMappingExecutor;
import com.garganttua.core.mapper.rules.SimpleCollectionMappingExecutor;
import com.garganttua.core.mapper.rules.SimpleFieldMappingExecutor;
import com.garganttua.core.mapper.rules.SimpleMapableFieldMappingExecutor;
import com.garganttua.core.reflection.IClass;
import com.garganttua.core.reflection.IField;
import com.garganttua.core.reflection.IMethod;
import com.garganttua.core.reflection.IObjectQuery;
import com.garganttua.core.reflection.IReflection;
import com.garganttua.core.reflection.ObjectAddress;
import com.garganttua.core.reflection.ReflectionException;

/**
 * Parses, validates and resolves executors for the {@link MappingRule}s of a
 * source/destination pair.
 *
 * <p>Rules originate from {@code @FieldMappingRule} / {@code @ObjectMappingRule}
 * annotations (source-aware, ranked exact &gt; most-specific assignable &gt; wildcard)
 * or are generated by convention for same-named fields. {@link #getRuleExecutor}
 * selects the concrete {@link IMappingRuleExecutor} (simple, collection, map,
 * implicit-conversion, method or nested-mapable) for each resolved field pair.
 */
public class MappingRules {
    private static final Logger log = Logger.getLogger(MappingRules.class);

	private final IReflection reflection;

	@SuppressWarnings("rawtypes")
	private final IClass<Collection> collectionClass;
	@SuppressWarnings("rawtypes")
	private final IClass<Map> mapClass;

	/**
	 * Creates a rule resolver backed by the given reflection facade.
	 *
	 * @param reflection the reflection provider used to resolve classes, fields and methods
	 */
	public MappingRules(IReflection reflection) {
		this.reflection = reflection;
		this.collectionClass = reflection.getClass(Collection.class);
		this.mapClass = reflection.getClass(Map.class);
	}

	/**
	 * Backward-compatible parse — equivalent to {@link #parse(IClass, IClass)} with
	 * a {@code null} source. Only wildcard mapping rules ({@code source = void.class},
	 * which is the default) are applied; typed rules are ignored because no
	 * source is provided to match against.
	 */
	public List<MappingRule> parse(IClass<?> destinationClass) throws MapperException {
		return this.parse(destinationClass, null);
	}

	/**
	 * Source-aware parsing. Annotation resolution picks at most one rule per field
	 * (and per class for {@code @ObjectMappingRule}) by ranking candidates:
	 * exact match on {@code source()} &gt; most-specific assignable &gt; wildcard
	 * ({@code source == void.class}). Ambiguity and duplicates throw at parse time.
	 */
	public List<MappingRule> parse(IClass<?> destinationClass, IClass<?> sourceClass) throws MapperException {
		log.debug("Parsing mapping rules for {} (source={})",
				destinationClass.getSimpleName(),
				sourceClass != null ? sourceClass.getSimpleName() : "<wildcard>");
		List<MappingRule> mappingRules = new ArrayList<>();
		List<MappingRule> result = this.recursiveParsing(destinationClass, sourceClass, mappingRules, "");
		log.debug("Parsed {} rules for {}", result.size(), destinationClass.getSimpleName());
		return result;
	}

	private List<MappingRule> recursiveParsing(IClass<?> destinationClass, IClass<?> sourceClass,
			List<MappingRule> mappingRules, String fieldAddress) throws MapperException {
		try {
			boolean objectMapping = false;
			IClass<ObjectMappingRule> objectMappingRuleClass = this.reflection.getClass(ObjectMappingRule.class);
			ObjectMappingRule[] classRules = destinationClass.getDeclaredAnnotationsByType(objectMappingRuleClass);
			ObjectMappingRule pickedClassRule = resolveBestMatching(classRules, sourceClass,
					ObjectMappingRule::source, "class " + destinationClass.getSimpleName());
			if (pickedClassRule != null) {
				ObjectAddress fromSourceMethod = new ObjectAddress(pickedClassRule.fromSourceMethod());
				ObjectAddress toSourceMethod = new ObjectAddress(pickedClassRule.toSourceMethod());
				mappingRules.add(new MappingRule(null, null, destinationClass, fromSourceMethod, toSourceMethod));
				objectMapping = true;
			}

			IClass<FieldMappingRule> fieldMappingRuleClass = this.reflection.getClass(FieldMappingRule.class);
			for (IField field : destinationClass.getDeclaredFields()) {
				FieldMappingRule[] fieldRules = field.getDeclaredAnnotationsByType(fieldMappingRuleClass);
				FieldMappingRule pickedField = (fieldRules.length == 0) ? null
						: resolveBestMatching(fieldRules, sourceClass,
								FieldMappingRule::source,
								"field " + destinationClass.getSimpleName() + "." + field.getName());
				if (pickedField != null && !objectMapping) {
					addFieldRule(pickedField, field, destinationClass, fieldAddress, mappingRules);
				} else {
					recurseIntoFieldType(field, sourceClass, mappingRules, fieldAddress);
				}
			}
			IClass<?> superclass = destinationClass.getSuperclass();
			if (superclass != null) {
				this.recursiveParsing(superclass, sourceClass, mappingRules, fieldAddress);
			}

			return mappingRules;
		} catch (ReflectionException e) {
			throw new MapperException(e);
		}
	}

	/** Record a single annotated field mapping rule (with optional from/to source converter methods). */
	private void addFieldRule(FieldMappingRule pickedField, IField field, IClass<?> destinationClass,
			String fieldAddress, List<MappingRule> mappingRules) {
		ObjectAddress fromSourceMethod = pickedField.fromSourceMethod().isEmpty() ? null
				: new ObjectAddress(pickedField.fromSourceMethod());
		ObjectAddress toSourceMethod = pickedField.toSourceMethod().isEmpty() ? null
				: new ObjectAddress(pickedField.toSourceMethod());
		ObjectAddress sourceFieldAddress = new ObjectAddress(pickedField.sourceFieldAddress());
		ObjectAddress destFieldAddress = new ObjectAddress(fieldAddress + field.getName());
		mappingRules.add(new MappingRule(sourceFieldAddress, destFieldAddress, destinationClass,
				fromSourceMethod, toSourceMethod));
	}

	/** Recurse into a non-annotated field's structural type (array element, collection element, map key/value). */
	private void recurseIntoFieldType(IField field, IClass<?> sourceClass, List<MappingRule> mappingRules,
			String fieldAddress) throws MapperException {
		IClass<?> fieldType = field.getType();
		String base = fieldAddress + field.getName() + ObjectAddress.ELEMENT_SEPARATOR;
		if (isNotPrimitive(fieldType) && !collectionClass.isAssignableFrom(fieldType)
				&& !mapClass.isAssignableFrom(fieldType) && fieldType.isArray()) {
			this.recursiveParsing(fieldType, sourceClass, mappingRules, base);
		} else if (collectionClass.isAssignableFrom(fieldType)) {
			IClass<?> genericType = getFieldGenericType(field, 0);
			if (genericType != null) {
				this.recursiveParsing(genericType, sourceClass, mappingRules, base);
			}
		} else if (mapClass.isAssignableFrom(fieldType)) {
			IClass<?> keyType = getFieldGenericType(field, 0);
			IClass<?> valueType = getFieldGenericType(field, 1);
			if (keyType != null) {
				this.recursiveParsing(keyType, sourceClass, mappingRules,
						base + ObjectAddress.MAP_KEY_INDICATOR + ObjectAddress.ELEMENT_SEPARATOR);
			}
			if (valueType != null) {
				this.recursiveParsing(valueType, sourceClass, mappingRules,
						base + ObjectAddress.MAP_VALUE_INDICATOR + ObjectAddress.ELEMENT_SEPARATOR);
			}
		}
	}

	@FunctionalInterface
	private interface SourceExtractor<A> {
		Class<?> sourceOf(A annotation);
	}

	/**
	 * Pick the single best-matching annotation for a given source class.
	 * Order: exact match &gt; most-specific assignable &gt; wildcard.
	 * Throws {@link MapperException} on duplicate exact, duplicate wildcard, or
	 * incomparable assignable matches.
	 */
	private <A> A resolveBestMatching(A[] candidates, IClass<?> sourceClass,
			SourceExtractor<A> sourceOf, String memberLabel) throws MapperException {
		if (candidates == null || candidates.length == 0) {
			return null;
		}

		Class<?> actualSource = (sourceClass == null) ? null : (Class<?>) sourceClass.getType();

		A exact = null;
		A wildcard = null;
		List<A> assignable = new ArrayList<>();

		for (A candidate : candidates) {
			Class<?> declared = sourceOf.sourceOf(candidate);
			if (declared == void.class) {
				if (wildcard != null) {
					throw new MapperException("Duplicate wildcard mapping rule on " + memberLabel);
				}
				wildcard = candidate;
			} else if (actualSource != null && declared.equals(actualSource)) {
				if (exact != null) {
					throw new MapperException("Duplicate mapping rule for source "
							+ declared.getName() + " on " + memberLabel);
				}
				exact = candidate;
			} else if (actualSource != null && declared.isAssignableFrom(actualSource)) {
				assignable.add(candidate);
			}
		}

		if (exact != null) {
			return exact;
		}

		if (!assignable.isEmpty()) {
			return mostSpecificAssignable(assignable, sourceOf, memberLabel, actualSource);
		}

		return wildcard;
	}

	/**
	 * From the assignable candidates, return the single most-specific (undominated)
	 * one, or throw when two incomparable candidates both match.
	 */
	private <A> A mostSpecificAssignable(List<A> assignable, SourceExtractor<A> sourceOf,
			String memberLabel, Class<?> actualSource) throws MapperException {
		A best = null;
		for (A candidate : assignable) {
			Class<?> candidateSrc = sourceOf.sourceOf(candidate);
			boolean dominated = false;
			for (A other : assignable) {
				if (other == candidate) {
					continue;
				}
				Class<?> otherSrc = sourceOf.sourceOf(other);
				if (!otherSrc.equals(candidateSrc) && candidateSrc.isAssignableFrom(otherSrc)) {
					dominated = true;
					break;
				}
			}
			if (!dominated) {
				if (best != null) {
					throw new MapperException("Ambiguous mapping rules on " + memberLabel
							+ " for source " + actualSource.getName()
							+ " (multiple incomparable matching source types)");
				}
				best = candidate;
			}
		}
		return best;
	}

	/**
	 * Validates that each rule's source/destination fields exist and that any
	 * declared converter method has a compatible one-parameter signature.
	 *
	 * @param sourceClass the class whose fields the rules are resolved against
	 * @param rules the rules to validate
	 * @throws MapperException if a field or method is missing or has an incompatible signature
	 */
	public void validate(IClass<?> sourceClass, List<MappingRule> rules) throws MapperException {
		log.debug("Validating {} rules for {}", rules.size(), sourceClass.getSimpleName());
		try {
			IObjectQuery<?> sourceQuery = this.reflection.query(sourceClass);
			for (MappingRule rule : rules) {
				this.validate(sourceQuery, rule);
			}
		} catch (ReflectionException e) {
			throw new MapperException(e);
		}
	}

	private void validate(IObjectQuery<?> sourceQuery, MappingRule rule)
			throws MapperException {
		try {
			IObjectQuery<?> destQuery = this.reflection.query(rule.destinationClass());

			List<Object> sourceField_ = sourceQuery.find(rule.sourceFieldAddress());
			List<Object> destField_ = destQuery.find(rule.destinationFieldAddress());

			IField sourceField = (IField) sourceField_.get(sourceField_.size() - 1);
			IField destField = (IField) destField_.get(destField_.size() - 1);

			if (rule.fromSourceMethodAddress() != null) {
				List<Object> fromMethod_ = destQuery.find(rule.fromSourceMethodAddress());
				IMethod fromMethod = (IMethod) fromMethod_.get(fromMethod_.size() - 1);
				MappingRules.validateMethod(rule, sourceField, destField, fromMethod);
			}
			if (rule.toSourceMethodAddress() != null) {
				List<Object> toMethod_ = destQuery.find(rule.toSourceMethodAddress());
				IMethod toMethod = (IMethod) toMethod_.get(toMethod_.size() - 1);
				MappingRules.validateMethod(rule, destField, sourceField, toMethod);
			}
		} catch (ReflectionException e) {
			throw new MapperException(e);
		}
	}

	private static void validateMethod(MappingRule rule, IField sourceField, IField destField, IMethod method)
			throws MapperException {
		if (method.getParameterTypes().length != 1) {
			throw new MapperException("Invalid method " + method.getName() + " of class "
					+ rule.destinationClass().getSimpleName() + " : must have exactly one parameter");
		}

		IClass<?> paramType = method.getParameterTypes()[0];
		IClass<?> returnType = method.getReturnType();

		if (!paramType.getType().equals(sourceField.getType().getType())) {
			throw new MapperException(
					"Invalid method " + method.getName() + " of class " + rule.destinationClass().getSimpleName()
							+ " : parameter must be of type " + sourceField.getType().getType());
		}

		if (!returnType.getType().equals(destField.getType().getType())) {
			throw new MapperException("Invalid method " + method.getName() + " of class "
					+ rule.destinationClass().getSimpleName() + " : return type must be " + destField.getType().getType());
		}
	}

	/**
	 * Resolves the source/destination fields (and optional converter method) for a
	 * rule and selects the matching {@link IMappingRuleExecutor}.
	 *
	 * @param mapper the owning mapper, passed to executors needing recursive mapping
	 * @param mappingDirection {@code REGULAR} or {@code REVERSE}; swaps source/destination roles
	 * @return the chosen executor, or {@code null} if no executor fits the resolved field pair
	 * @throws MapperException if field/method resolution fails
	 */
	public IMappingRuleExecutor getRuleExecutor(IMapper mapper, MappingDirection mappingDirection,
			MappingRule rule, IClass<?> sourceClass, IClass<?> destinationClass) throws MapperException {
		log.debug("Resolving executor for {} -> {} ({})", sourceClass.getSimpleName(), destinationClass.getSimpleName(), mappingDirection);

		List<Object> destinationField = null;
		List<Object> sourceField = null;
		List<Object> mappingMethod = null;

		try {
			if (mappingDirection == MappingDirection.REGULAR) {
				if (rule.fromSourceMethodAddress() != null) {
					mappingMethod = this.reflection.query(destinationClass)
							.find(rule.fromSourceMethodAddress());
				}
				sourceField = this.reflection.query(sourceClass).find(rule.sourceFieldAddress());
				destinationField = this.reflection.query(destinationClass)
						.find(rule.destinationFieldAddress());
			} else {
				if (rule.toSourceMethodAddress() != null) {
					mappingMethod = this.reflection.query(sourceClass)
							.find(rule.toSourceMethodAddress());
				}
				sourceField = this.reflection.query(sourceClass).find(rule.destinationFieldAddress());
				destinationField = this.reflection.query(destinationClass).find(rule.sourceFieldAddress());
			}

			IField sourceFieldLeaf = (IField) sourceField.get(sourceField.size() - 1);
			IField destinationFieldLeaf = (IField) destinationField.get(destinationField.size() - 1);

			IMappingRuleExecutor executor = selectExecutor(mapper, mappingDirection,
					sourceFieldLeaf, destinationFieldLeaf, mappingMethod);
			if (executor != null) {
				return executor;
			}

			log.warn("No suitable executor found for rule: {}", rule);

		} catch (ReflectionException e) {
			throw new MapperException(e);
		}
		return null;
	}

	/** Choose the executor implementation for a resolved (source field, dest field) pair; null if none fits. */
	private IMappingRuleExecutor selectExecutor(IMapper mapper, MappingDirection mappingDirection,
			IField sourceFieldLeaf, IField destinationFieldLeaf, List<Object> mappingMethod) {
		IClass<?> sourceFieldType = sourceFieldLeaf.getType();
		IClass<?> destFieldType = destinationFieldLeaf.getType();

		if (mappingMethod != null) {
			IMethod methodLeaf = (IMethod) mappingMethod.get(mappingMethod.size() - 1);
			return new MethodMappingExecutor(methodLeaf, sourceFieldLeaf, destinationFieldLeaf, mappingDirection);
		}
		if (mapClass.isAssignableFrom(sourceFieldType) && mapClass.isAssignableFrom(destFieldType)) {
			return mapExecutor(mapper, sourceFieldLeaf, destinationFieldLeaf);
		}
		if (collectionClass.isAssignableFrom(sourceFieldType) && collectionClass.isAssignableFrom(destFieldType)) {
			return collectionExecutor(mapper, sourceFieldLeaf, destinationFieldLeaf);
		}
		if (sourceFieldType.getType().equals(destFieldType.getType())) {
			return new SimpleFieldMappingExecutor(this.reflection, sourceFieldLeaf, destinationFieldLeaf);
		}
		// Try implicit conversion before falling back to mapable field.
		java.util.Optional<java.util.function.Function<Object, Object>> conv =
				ImplicitConversions.findConversion(sourceFieldType, destFieldType);
		if (conv.isPresent()) {
			return new ImplicitConversionMappingExecutor(this.reflection, sourceFieldLeaf, destinationFieldLeaf, conv.get());
		}
		if (!isArrayOrMapOrCollection(sourceFieldLeaf) && !isArrayOrMapOrCollection(destinationFieldLeaf)) {
			return new SimpleMapableFieldMappingExecutor(this.reflection, mapper, sourceFieldLeaf, destinationFieldLeaf);
		}
		return null;
	}

	/** Executor for a Map&lt;K,V&gt; field pair: simple copy when key/value types match, else element-mapping. */
	private IMappingRuleExecutor mapExecutor(IMapper mapper, IField sourceFieldLeaf, IField destinationFieldLeaf) {
		IClass<?> srcKeyType = getFieldGenericType(sourceFieldLeaf, 0);
		IClass<?> srcValType = getFieldGenericType(sourceFieldLeaf, 1);
		IClass<?> dstKeyType = getFieldGenericType(destinationFieldLeaf, 0);
		IClass<?> dstValType = getFieldGenericType(destinationFieldLeaf, 1);
		boolean keysMatch = srcKeyType != null && dstKeyType != null
				&& srcKeyType.getType().equals(dstKeyType.getType());
		boolean valsMatch = srcValType != null && dstValType != null
				&& srcValType.getType().equals(dstValType.getType());
		if (keysMatch && valsMatch) {
			return new SimpleFieldMappingExecutor(this.reflection, sourceFieldLeaf, destinationFieldLeaf);
		}
		return new MapableMapMappingExecutor(this.reflection, mapper, sourceFieldLeaf, destinationFieldLeaf);
	}

	/** Executor for a Collection field pair: simple/collection copy when element types match, else element-mapping. */
	private IMappingRuleExecutor collectionExecutor(IMapper mapper, IField sourceFieldLeaf, IField destinationFieldLeaf) {
		IClass<?> sourceFieldType = sourceFieldLeaf.getType();
		IClass<?> destFieldType = destinationFieldLeaf.getType();
		IClass<?> sourceGenericType = getFieldGenericType(sourceFieldLeaf, 0);
		IClass<?> destGenericType = getFieldGenericType(destinationFieldLeaf, 0);
		boolean genericsMatch = sourceGenericType != null
				&& sourceGenericType.getType().equals(destGenericType != null ? destGenericType.getType() : null);
		boolean sameContainer = sourceFieldType.getType().equals(destFieldType.getType());
		if (sameContainer && genericsMatch) {
			return new SimpleFieldMappingExecutor(this.reflection, sourceFieldLeaf, destinationFieldLeaf);
		}
		if (!sameContainer && genericsMatch) {
			return new SimpleCollectionMappingExecutor(this.reflection, sourceFieldLeaf, destinationFieldLeaf);
		}
		return new MapableCollectionMappingExecutor(this.reflection, mapper, sourceFieldLeaf, destinationFieldLeaf);
	}

	/**
	 * Generates convention-based rules pairing destination fields with same-named
	 * source fields, recursing through superclasses and skipping static, transient,
	 * synthetic and {@code @MappingIgnore} fields.
	 *
	 * @return the generated rules (empty if no field names match)
	 */
	public List<MappingRule> generateConventionRules(IClass<?> source, IClass<?> destination) {
		log.debug("Generating convention rules: {} -> {}", source.getSimpleName(), destination.getSimpleName());
		List<MappingRule> rules = new ArrayList<>();
		IClass<MappingIgnore> mappingIgnoreClass;
		try {
			mappingIgnoreClass = this.reflection.getClass(MappingIgnore.class);
		} catch (Exception e) {
			mappingIgnoreClass = null;
		}
		generateConventionRulesRecursive(source, destination, rules, mappingIgnoreClass);
		log.debug("Generated {} convention rules", rules.size());
		return rules;
	}

	private void generateConventionRulesRecursive(IClass<?> source, IClass<?> destination,
			List<MappingRule> rules, IClass<MappingIgnore> mappingIgnoreClass) {
		for (IField destField : destination.getDeclaredFields()) {
			int modifiers = destField.getModifiers();
			if (java.lang.reflect.Modifier.isStatic(modifiers)
					|| java.lang.reflect.Modifier.isTransient(modifiers)
					|| destField.isSynthetic()) {
				continue;
			}
			if (mappingIgnoreClass != null && destField.isAnnotationPresent(mappingIgnoreClass)) {
				continue;
			}

			String fieldName = destField.getName();
			if (hasField(source, fieldName)) {
				ObjectAddress srcAddr = new ObjectAddress(fieldName);
				ObjectAddress destAddr = new ObjectAddress(fieldName);
				rules.add(new MappingRule(srcAddr, destAddr, destination, null, null));
			}
		}

		IClass<?> superclass = destination.getSuperclass();
		if (superclass != null && !superclass.getName().equals("java.lang.Object")) {
			generateConventionRulesRecursive(source, superclass, rules, mappingIgnoreClass);
		}
	}

	private boolean hasField(IClass<?> clazz, String fieldName) {
		IClass<?> current = clazz;
		while (current != null && !current.getName().equals("java.lang.Object")) {
			for (IField field : current.getDeclaredFields()) {
				if (field.getName().equals(fieldName)) {
					return true;
				}
			}
			current = current.getSuperclass();
		}
		return false;
	}

	private IClass<?> getFieldGenericType(IField field, int index) {
		Type genericType = field.getGenericType();
		if (genericType instanceof ParameterizedType parameterizedType) {
			Type[] typeArguments = parameterizedType.getActualTypeArguments();
			if (typeArguments.length > index && typeArguments[index] instanceof Class<?> clazz) {
				return this.reflection.getClass(clazz);
			}
		}
		return null;
	}

	private boolean isArrayOrMapOrCollection(IField field) {
		IClass<?> type = field.getType();
		return collectionClass.isAssignableFrom(type)
				|| mapClass.isAssignableFrom(type)
				|| type.isArray();
	}

	static boolean isNotPrimitive(IClass<?> clazz) {
		if (clazz.isPrimitive()) {
			return false;
		}
		String name = clazz.getName();
		if (name.equals("java.lang.Integer") || name.equals("java.lang.Long")
				|| name.equals("java.lang.Float") || name.equals("java.lang.Double")
				|| name.equals("java.lang.Short") || name.equals("java.lang.Byte")
				|| name.equals("java.lang.Character") || name.equals("java.lang.Boolean")
				|| name.equals("java.lang.String") || name.equals("java.util.Date")) {
			return false;
		}
		return true;
	}
}
