# This workflow will build a package using Maven on every push
# and then publish it to GitHub Packages when a push occurs on 'dev' or a tag is created on 'main'

name: Maven Package

on:
  push:
    branches: 
      - "**"  # Build on any branch push
    tags:
      - "*"  # Trigger on any tag creation

  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
<<<<<<< HEAD
<<<<<<< HEAD
        server-id: github garganttua tooling
        settings-path: ${{ github.workspace }} # location for the settings.xml file
=======
>>>>>>> 282b907 (Update maven-publish.yml)
=======
        server-id: github garganttua tooling
        settings-path: ${{ github.workspace }} # location for the settings.xml file
>>>>>>> dc8a944 (Update maven-publish.yml)

    - name: Deploy to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
